// Generates src/page/constants.ts from set_constantValues() in CryptoPro's cadesplugin_api.js
// (vendor/, pinned in vendor-lock.json). Sites read these values off window.cadesplugin, so ours
// must be the same set with the same values. Run after pinning a new cadesplugin_api.js.
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { readLock, repoRoot, vendorPath } from "./fetch-vendor.ts";

export const constantsFile = join(repoRoot, "src", "page", "constants.ts");

// Returns the constants in source order; a name assigned twice keeps its last value, as at runtime.
export function extractConstants(source: string): Map<string, number | string> {
  const start = source.indexOf("function set_constantValues()");
  if (start < 0) throw new Error("set_constantValues() not found in cadesplugin_api.js");
  const end = source.indexOf("\n    }", start);
  const body = source.slice(start, end);
  const constants = new Map<string, number | string>();
  for (const line of body.split("\n").slice(1)) {
    if (line.trim() === "") continue;
    const match = /^\s*cadesplugin\.(\w+) = (.+);\s*$/.exec(line);
    if (!match) throw new Error(`unexpected line in set_constantValues(): ${line}`);
    const [, name, literal] = match as unknown as [string, string, string];
    const value: unknown = literal.startsWith('"') ? JSON.parse(literal) : Number(literal);
    if (typeof value === "number" && Number.isNaN(value)) throw new Error(`not a literal: ${line}`);
    constants.set(name, value as number | string);
  }
  return constants;
}

export function renderConstants(constants: Map<string, number | string>, sourceSha256: string): string {
  const lines = [...constants].map(([name, value]) => `  ${name}: ${JSON.stringify(value)},`);
  return [
    "// Generated by scripts/gen-constants.ts from cadesplugin_api.js 2.4.5",
    `// (SHA-256 ${sourceSha256}). Do not edit by hand.`,
    "export const constants = {",
    ...lines,
    "} as const;",
    "",
  ].join("\n");
}

export function generateConstants(): string {
  const source = readFileSync(vendorPath("cryptopro-cadesplugin_api-js"), "utf8");
  const sha256 = readLock()["cryptopro-cadesplugin_api-js"]!.sha256;
  return renderConstants(extractConstants(source), sha256);
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  writeFileSync(constantsFile, generateConstants());
  console.log(`wrote ${constantsFile}`);
}
