// Regenerates src/extension/builtin-roots.ts, the certificates the root store starts with, from CryptoPro's
// lsb-cprocsp-ca-certs package: the files in var/opt/cprocsp/tmpcerts/root, which its postinst installs into
// the root store (the ones in tmpcerts/ca go to the intermediate store and are not taken). The package comes
// with CryptoPro CSP (linux-amd64_deb.tgz, after logging in to CryptoPro's site); it is not kept in the repo.
//
// Usage: node scripts/import-roots.ts path/to/lsb-cprocsp-ca-certs_<version>_all.deb
import { execFileSync } from "node:child_process";
import { mkdtempSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { repoRoot } from "./fetch-vendor.ts";
import { formatName } from "../src/page/dn.ts";
import { derToBase64, parseCertificate } from "../src/page/x509.ts";

export const builtinRootsFile = join(repoRoot, "src", "extension", "builtin-roots.ts");

function field(deb: string, name: string): string {
  return execFileSync("dpkg-deb", ["-f", deb, name], { encoding: "utf8" }).trim();
}

export function importRoots(deb: string): number {
  if (field(deb, "Package") !== "lsb-cprocsp-ca-certs") throw new Error(`${deb} is not lsb-cprocsp-ca-certs`);
  const version = field(deb, "Version");
  const work = mkdtempSync(join(tmpdir(), "roots-"));
  try {
    execFileSync("dpkg-deb", ["-x", deb, work]);
    const dir = join(work, "var", "opt", "cprocsp", "tmpcerts", "root");
    const entries = readdirSync(dir)
      .filter((name) => name.endsWith(".cer"))
      .map((name) => {
        const certificate = parseCertificate(new Uint8Array(readFileSync(join(dir, name))));
        // The package names each file after its SHA-1 thumbprint; a mismatch means we read it wrong.
        if (name.replace(/\.cer$/, "").toUpperCase() !== certificate.thumbprint) {
          throw new Error(`${name}: thumbprint is ${certificate.thumbprint}`);
        }
        return certificate;
      })
      .sort((a, b) => a.thumbprint.localeCompare(b.thumbprint));
    const lines = [
      "// Generated by scripts/import-roots.ts, do not edit. The root certificates CryptoPro CSP installs into the",
      `// root store, from lsb-cprocsp-ca-certs ${version} (var/opt/cprocsp/tmpcerts/root), as base64 DER.`,
      "export const BUILTIN_ROOTS_SOURCE = " + JSON.stringify(`lsb-cprocsp-ca-certs ${version}`) + ";",
      "",
      "export const BUILTIN_ROOTS: readonly string[] = [",
      ...entries.flatMap((certificate) => [
        `  // ${certificate.thumbprint} ${formatName(certificate.subject)}`,
        `  "${derToBase64(certificate.der)}",`,
      ]),
      "];",
      "",
    ];
    writeFileSync(builtinRootsFile, lines.join("\n"));
    return entries.length;
  } finally {
    rmSync(work, { recursive: true, force: true });
  }
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const deb = process.argv[2];
  if (!deb) {
    console.error("usage: node scripts/import-roots.ts path/to/lsb-cprocsp-ca-certs_<version>_all.deb");
    process.exit(2);
  }
  console.log(`${importRoots(deb)} certificates written to ${builtinRootsFile}`);
}
